#!/bin/bash                                                 
#PBS -N GALAH_Li
#PBS -l ncpus=46
#PBS -l mem=180GB
#PBS -q normal
#PBS -l walltime=10:00:00
#PBS -lstorage=gdata/y89+scratch/y89
#PBS -P hl99
#PBS -r y

module unload python3
module load python3/3.7.4

cd /g/data1a/y89/xw5841/galah_rv_const

python3 main_pool.py --save_fit --load_fit 
#python3 main.py --save_fit --load_fit --sid 150607003601353
