#!/bin/bash                                                 
#PBS -N GALAH_${key}
#PBS -l ncpus=48
#PBS -l mem=180GB
#PBS -q normal
#PBS -l walltime=48:00:00
#PBS -lstorage=gdata/y89+scratch/y89
#PBS -P y89
#PBS -r y

module unload python3
module load python3/3.7.4

cd ${main_directory}

python3 main.py -k ${key} --load_fit --save_fit --threads 48
